import { initializeApp, getApps } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import { getFirestore, collection, onSnapshot, query, where } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";
const cfg={apiKey:"AIzaSyD13MXR0ZQSjPJBxQKYPmsMKjl4yzU2hSs",authDomain:"steadfast-1d0e6.firebaseapp.com",projectId:"steadfast-1d0e6",storageBucket:"steadfast-1d0e6.firebasestorage.app",messagingSenderId:"488385339804",appId:"1:488385339804:web:0d2bcf3967a8f95ccfe859"};
const app=getApps().length?getApps()[0]:initializeApp(cfg),db=getFirestore(app);const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function previewUrl(u){return /^https?:\/\//i.test(String(u||""))?String(u):"";}
function livePreview(url,title){
  const u=previewUrl(url);
  if(!u)return `<div class="sf-preview-empty">NO LIVE PREVIEW</div>`;
  const shot=`https://image.thum.io/get/width/1400/crop/900/noanimate/${u}`;
  return `<div class="sf-live-frame" data-live-frame data-url="${esc(u)}"><iframe src="${esc(u)}" title="${esc(title)} live preview" loading="eager" allow="fullscreen"></iframe><div class="sf-live-fallback"><img src="${esc(shot)}" alt="${esc(title)} website preview" loading="lazy"><div><strong>Live page preview</strong><span>The website may block embedded viewing. The preview image is shown as a fallback.</span><a href="${esc(u)}" target="_blank" rel="noopener">Open live website ↗</a></div></div></div>`;
}
function card(p){const img=p.previewUrl?livePreview(p.previewUrl,p.title):(Array.isArray(p.previewImages)&&p.previewImages[0]?`<img src="${esc(p.previewImages[0])}" alt="${esc(p.title)} preview">`:`<div class="sf-preview-empty">LIVE PREVIEW</div>`);return `<article class="sf-work-card"><div class="sf-work-preview">${img}</div><div class="sf-work-body"><span class="sf-work-tag">${esc(p.category||'PROJECT')}</span><h3>${esc(p.title||'Untitled Project')}</h3><p>${esc(p.description||'')}</p><div class="sf-objective"><b>Objective</b><br>${esc(p.objective||'')}</div><div class="sf-work-actions">${p.previewUrl?`<a class="btn ghost" href="${esc(p.previewUrl)}" target="_blank" rel="noopener">Live Preview ↗</a>`:''}${p.visitUrl?`<a class="btn primary" href="${esc(p.visitUrl)}" target="_blank" rel="noopener">Visit ↗</a>`:''}</div></div></article>`}
function activateLiveFallbacks(root=document){root.querySelectorAll('[data-live-frame]').forEach(w=>{const iframe=w.querySelector('iframe');const fallback=w.querySelector('.sf-live-fallback');let timer=setTimeout(()=>{if(fallback)fallback.classList.add('show');},5500);iframe?.addEventListener('load',()=>{clearTimeout(timer);});});}
const grid=document.getElementById('steadfastWorksGrid');if(grid){onSnapshot(query(collection(db,'portfolioProjects'),where('published','==',true)),snap=>{const items=snap.docs.map(d=>({id:d.id,...d.data()})).filter(p=>p.published).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));grid.innerHTML=items.length?items.map(card).join(''):'<div class="sf-empty-store"><strong>No additional published projects.</strong><span>Published customer projects will appear here after purchase confirmation.</span></div>';activateLiveFallbacks(grid);},err=>{console.warn('Works load error',err);grid.innerHTML='<div class="sf-empty-store"><strong>Projects temporarily unavailable.</strong><span>Please try again shortly.</span></div>';});}
