import { initializeApp, getApps } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signOut } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
const cfg={apiKey:"AIzaSyD13MXR0ZQSjPJBxQKYPmsMKjl4yzU2hSs",authDomain:"steadfast-1d0e6.firebaseapp.com",projectId:"steadfast-1d0e6",storageBucket:"steadfast-1d0e6.firebasestorage.app",messagingSenderId:"488385339804",appId:"1:488385339804:web:0d2bcf3967a8f95ccfe859"};
const app=getApps().length?getApps()[0]:initializeApp(cfg),auth=getAuth(app);const $=id=>document.getElementById(id);let mode="login";const params=new URLSearchParams(location.search);const returnTo=params.get("return")||"store.html";
function status(text,error=false){const el=$("accountStatus");el.textContent=text;el.hidden=false;el.classList.toggle("error",error)}
function setMode(next){mode=next;$("loginTab").classList.toggle("active",mode==="login");$("registerTab").classList.toggle("active",mode==="register");$("accountTitle").textContent=mode==="login"?"Sign in.":"Create your account.";$("accountIntro").textContent=mode==="login"?"Sign in to purchase products, access your purchases, and leave verified buyer reviews.":"Create a STEADFAST customer account using your email and a password.";$("confirmWrap").hidden=mode!=="register";$("accountSubmit").textContent=mode==="login"?"Sign in →":"Create account →";$("accountPassword").autocomplete=mode==="login"?"current-password":"new-password";$("accountStatus").hidden=true}
$("loginTab").onclick=()=>setMode("login");$("registerTab").onclick=()=>setMode("register");
$("accountForm").addEventListener("submit",async e=>{e.preventDefault();const email=$("accountEmail").value.trim().toLowerCase(),pw=$("accountPassword").value;if(mode==="register"&&pw!==$("accountConfirm").value)return status("Passwords do not match.",true);try{status(mode==="login"?"Signing in…":"Creating account…");if(mode==="login")await signInWithEmailAndPassword(auth,email,pw);else await createUserWithEmailAndPassword(auth,email,pw);location.href=returnTo}catch(err){console.error(err);status(err?.message||"Account action failed.",true)}});
onAuthStateChanged(auth,u=>{if(u&&!params.has("force")){status(`Signed in as ${u.email}. Redirecting…`);setTimeout(()=>location.href=returnTo,250)}});
