import { initializeApp, getApps } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import { getAuth, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
import { getFirestore, doc, getDoc, setDoc, collection, query, where, getDocs } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";
const cfg={apiKey:"AIzaSyD13MXR0ZQSjPJBxQKYPmsMKjl4yzU2hSs",authDomain:"steadfast-1d0e6.firebaseapp.com",projectId:"steadfast-1d0e6",storageBucket:"steadfast-1d0e6.firebasestorage.app",messagingSenderId:"488385339804",appId:"1:488385339804:web:0d2bcf3967a8f95ccfe859"};
const app=getApps().length?getApps()[0]:initializeApp(cfg),auth=getAuth(app),db=getFirestore(app); const $=id=>document.getElementById(id);
let currentUser=null,profile=null,orders=[],access=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateVal=v=>v?.toDate?v.toDate():v?.seconds?new Date(v.seconds*1000):v?new Date(v):null;
const dateText=v=>{const d=dateVal(v);return d&&!isNaN(d)?d.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}):'—'};
const money=(n,c='PHP')=>{try{return new Intl.NumberFormat(undefined,{style:'currency',currency:c}).format(Number(n||0))}catch{return `${c} ${Number(n||0).toFixed(2)}`}};
function alertBox(msg){const el=$('cpAlert');el.hidden=false;el.className='cp-error';el.textContent=msg}
function switchPanel(name){document.querySelectorAll('.cp-panel').forEach(x=>x.classList.toggle('active',x.dataset.section===name));document.querySelectorAll('[data-panel]').forEach(x=>x.classList.toggle('active',x.dataset.panel===name));window.scrollTo({top:0,behavior:'smooth'})}
function buildNav(){const nav=$('cpMobileNav');nav.innerHTML=['overview','orders','products','profile','support'].map(n=>`<button class="cp-btn" data-panel="${n}">${n==='overview'?'Overview':n==='orders'?'My Orders':n==='products'?'My Products':n==='profile'?'Profile':'Support'}</button>`).join('')}
document.addEventListener('click',e=>{const b=e.target.closest('[data-panel]');if(b){e.preventDefault();switchPanel(b.dataset.panel)}const go=e.target.closest('[data-panel-go]');if(go)switchPanel(go.dataset.panelGo)});
async function loadProfile(){const snap=await getDoc(doc(db,'customerProfiles',currentUser.uid));profile=snap.exists()?snap.data():{uid:currentUser.uid,email:currentUser.email};return profile}
async function loadData(){const oq=query(collection(db,'storeOrders'),where('customerUid','==',currentUser.uid));const aq=query(collection(db,'customerAccess'),where('customerUid','==',currentUser.uid));const [os,as]=await Promise.all([getDocs(oq),getDocs(aq)]);orders=os.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(dateVal(b.createdAt)?.getTime()||0)-(dateVal(a.createdAt)?.getTime()||0));access=as.docs.map(d=>({id:d.id,...d.data()}));}
function render(){const first=profile?.firstName||currentUser.displayName?.split(' ')[0]||'Customer',last=profile?.lastName||'';$('cpSideName').textContent=`${first}${last?' '+last:''}`;$('cpIdentity').textContent=`${profile?.email||currentUser.email||''} · ${profile?.username?'@'+profile.username:'STEADFAST customer'}`;$('cpWelcome').textContent=`Welcome back, ${first}${last?' '+last:''}!`;$('cpSideUsername').textContent=profile?.username?`@${profile.username}`:'@customer';const initials=((first?.[0]||'')+(last?.[0]||'')).toUpperCase()||'C';$('cpAvatar').textContent=initials;$('cpUsername').textContent=profile?.username?`@${profile.username}`:'Customer';$('cpEmail').textContent=profile?.email||currentUser.email||'—';const verified=profile?.emailVerified===true||currentUser.emailVerified===true;$('cpVerifyBadge').textContent=verified?'Email verified':'Email not verified';$('cpSideVerified').textContent=verified?'Verified':'Not verified';$('statEmail').textContent=verified?'Verified':'Pending';$('statOrders').textContent=orders.length;$('statProducts').textContent=access.length;$('statStatus').textContent=verified?'Verified':'Pending';
 const recent=orders.slice(0,5);$('recentOrders').innerHTML=recent.length?recent.map(orderRow).join(''):`<div class="cp-empty">No orders yet. <a href="store.html" style="color:#c18cff">Browse the Store →</a></div>`;$('ordersList').innerHTML=orders.length?orders.map(orderRow).join(''):`<div class="cp-empty">You have no orders yet.</div>`;$('productsList').innerHTML=access.length?access.map(accessRow).join(''):`<div class="cp-empty">No paid product access yet. Products you purchase will appear here.</div>`;$('profileFirst').value=profile?.firstName||'';$('profileLast').value=profile?.lastName||'';$('profileUsername').value=profile?.username||'';$('profileEmail').value=profile?.email||currentUser.email||'';}
function orderRow(o){const st=String(o.status||'pending');return `<div class="cp-item"><div><strong>${esc(o.productName||'STEADFAST product')}</strong><span>${dateText(o.createdAt)} · ${money(o.amount,o.currency||'PHP')}</span></div><span class="cp-status ${esc(st)}">${esc(st)}</span></div>`}
function accessRow(a){const url=a.unlockUrl||a.previewUrl||'';return `<div class="cp-item"><div><strong>${esc(a.productName||a.name||'Unlocked product')}</strong><span>${esc(a.status||'paid')} · ${dateText(a.updatedAt||a.createdAt)}</span></div>${url?`<a class="cp-btn primary" href="${esc(url)}" target="_blank" rel="noopener">Open product →</a>`:'<span class="cp-status paid">Access ready</span>'}</div>`}
$('profileForm').addEventListener('submit',async e=>{e.preventDefault();if(!currentUser||!profile)return;const first=$('profileFirst').value.trim(),last=$('profileLast').value.trim(),username=$('profileUsername').value.trim().toLowerCase();if(!/^[a-z0-9._-]{3,24}$/.test(username)){ $('profileStatus').textContent='Username must be 3–24 characters using letters, numbers, dot, underscore or hyphen.';return}try{$('profileStatus').textContent='Saving…';const alias=await getDoc(doc(db,'customerUsernames',username));if(alias.exists()&&alias.data().uid!==currentUser.uid){$('profileStatus').textContent='That username is already taken.';return}await setDoc(doc(db,'customerProfiles',currentUser.uid),{firstName:first,lastName:last,username,updatedAt:new Date()},{merge:true});await setDoc(doc(db,'customerUsernames',username),{uid:currentUser.uid,email:currentUser.email,updatedAt:new Date()},{merge:true});profile={...profile,firstName:first,lastName:last,username};render();$('profileStatus').textContent='Profile saved successfully.'}catch(err){console.error(err);$('profileStatus').textContent=err?.message||'Profile could not be saved.'}});
$('cpSignOut').onclick=async()=>{try{await signOut(auth);location.href='store.html'}catch(e){alertBox(e?.message||'Could not sign out.')}};
onAuthStateChanged(auth,async u=>{if(!u){location.href='account.html?return=account.html&force=1';return}currentUser=u;buildNav();try{profile=await loadProfile();await loadData();render()}catch(err){console.error(err);alertBox('Your account loaded, but some portal data could not be displayed. Please refresh or try again later.');try{profile=await loadProfile();render()}catch{}}});
