import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getAuth, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";

const firebaseConfig={apiKey:"PASTE_FIREBASE_API_KEY",authDomain:"PASTE_FIREBASE_AUTH_DOMAIN",projectId:"PASTE_FIREBASE_PROJECT_ID",storageBucket:"PASTE_FIREBASE_STORAGE_BUCKET",messagingSenderId:"PASTE_FIREBASE_MESSAGING_SENDER_ID",appId:"PASTE_FIREBASE_APP_ID"};
const AUTHORIZED_EMAILS=["yahhclffjnd@gmail.com"];
const app=initializeApp(firebaseConfig),auth=getAuth(app);
onAuthStateChanged(auth,user=>{if(!user||!AUTHORIZED_EMAILS.includes((user.email||"").toLowerCase())) location.href="index.html";});
document.getElementById("logout").onclick=()=>signOut(auth);

const view=document.getElementById("view"), title=document.getElementById("pageTitle"), sub=document.getElementById("pageSub");
const rows=[["01","John Smith","E-commerce","2,400","USD","New","Sep 19, 2026"],["02","Maria Santos","Business Website","45,000","PHP","Contacted","Sep 18, 2026"],["03","Alex Brown","Portfolio","1,800","USD","Pending","Sep 18, 2026"],["04","Sofia Reyes","Restaurant Website","32,000","PHP","In Progress","Sep 17, 2026"],["05","Daniel Lee","Web Application","3,900","USD","Converted","Sep 16, 2026"]];
function table(){return `<div class="table-wrap"><table class="table"><thead><tr><th>#</th><th>Client</th><th>Website</th><th>Estimate</th><th>Currency</th><th>Status</th><th>Date</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr>${r.map((x,i)=>`<td>${i===5?`<span class="badge">${x}</span>`:x}</td>`).join("")}<td><button class="quick-view" data-client="${r[1]}" style="background:#191d29;border:1px solid #2a2f40;color:#ddd;border-radius:7px;padding:5px 8px;font-size:9px">View</button></td></tr>`).join("")}</tbody></table></div>`}
function dashboard(){title.textContent="Welcome back, Cliff!";sub.textContent="Here’s what’s happening with your website inquiries today.";view.innerHTML=`<div class="metrics">${[["12","New Quotes","↑ 20%"],["7","Pending","↑ 14%"],["3","Contacted","↑ 50%"],["2","In Progress","→ 0%"],["5","Converted","↑ 67%"]].map(x=>`<div class="metric"><b>${x[0]}</b><span>${x[1]}</span><span class="up">${x[2]} vs last week</span></div>`).join("")}</div><div class="grid"><section class="panel"><h2>Recent Website Quotations</h2><p class="muted">Latest inquiries from potential clients.</p>${table()}</section><aside><section class="panel"><h2>Integrations</h2><div class="notice">Gmail · Ready to connect</div><div class="notice">CRM · Not connected</div><div class="notice">Google Sheets · Ready</div></section><section class="panel" style="margin-top:15px"><h2>Quick Actions</h2><div class="quick"><button data-view="quotations">＋ New quotation</button><button data-view="leads">＋ Add lead</button><button data-view="email">✉ Compose email</button></div></section></aside></div>`}
function generic(name,description){title.textContent=name;sub.textContent=description;view.innerHTML=`<section class="panel"><h2>${name}</h2><p class="muted">${description}</p>${name==="Quotations"||name==="Leads"||name==="Clients"?table():`<div class="notice">This section is ready for the secure backend connection. Firebase/Google OAuth must be configured before live customer data is loaded.</div>`}</section>`}
const descriptions={quotations:"Manage incoming website quotation requests.",leads:"Track potential clients from inquiry to conversion.",clients:"Keep customer information organized.",email:"Communicate with customers through the dedicated STEADFAST work Gmail.",crm:"Connect your CRM through secure OAuth/API credentials.",analytics:"View quotation trends, project types, currencies, and conversion data.",settings:"Manage authorized admin access and connected services."};
function navigate(v){document.querySelectorAll("#nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===v)); if(v==="dashboard")dashboard(); else generic(v.charAt(0).toUpperCase()+v.slice(1),descriptions[v]||"");}
document.getElementById("nav").onclick=e=>{const b=e.target.closest("button[data-view]");if(b)navigate(b.dataset.view)};
document.getElementById("view").onclick=e=>{const b=e.target.closest(".quick-view");if(b)alert("Quotation: "+b.dataset.client+"\n\nLive customer data will load after Firebase/Firestore is connected.");};
document.querySelector(".content").addEventListener("click",e=>{const b=e.target.closest("[data-view]");if(b)navigate(b.dataset.view)});
document.getElementById("mobileMenu").onclick=()=>document.getElementById("sidebar").classList.toggle("open");
document.getElementById("search").addEventListener("input",e=>{const q=e.target.value.toLowerCase();document.querySelectorAll(".table tbody tr").forEach(tr=>tr.style.display=tr.textContent.toLowerCase().includes(q)?"":"none")});
dashboard();