// STEADFAST Gmail configuration
// The endpoint is generated by Google Apps Script and authorized with the Gmail account you choose.
// Do NOT put a Gmail password, OAuth refresh token, or client secret in this file.
window.STEADFAST_EMAIL_CONFIG = {
  provider: 'google-apps-script-gmail',
  endpoint: '',
  adminEmail: 'yahhclffjnd@gmail.com',
  senderName: 'STEADFAST by Cliff Jandee Medrano',
  replyTo: 'yahhclffjnd@gmail.com'
};
