import { initializeApp, getApps } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import { getFirestore, collection, getDocs, addDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyD13MXR0ZQSjPJBxQKYPmsMKjl4yzU2hSs",authDomain:"steadfast-1d0e6.firebaseapp.com",projectId:"steadfast-1d0e6",storageBucket:"steadfast-1d0e6.firebasestorage.app",messagingSenderId:"488385339804",appId:"1:488385339804:web:0d2bcf3967a8f95ccfe859"};
const app=getApps().length?getApps()[0]:initializeApp(firebaseConfig),db=getFirestore(app);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=(v,c="PHP")=>{try{return new Intl.NumberFormat(undefined,{style:"currency",currency:c}).format(Number(v||0))}catch{return `${c} ${Number(v||0).toFixed(2)}`}};
let products=[];
async function hashCode(value){const data=new TextEncoder().encode(value);const hash=await crypto.subtle.digest("SHA-256",data);return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,"0")).join("");}
function productCard(p){const stock=Math.max(0,Number(p.stock||0)),out=stock<1;return `<article class="sf-product-card"><div class="sf-product-preview sf-preview-button" role="button" tabindex="0" data-preview="${esc(p.id)}" aria-label="Preview ${esc(p.name)}">${p.previewUrl?`<iframe src="${esc(p.previewUrl)}" loading="lazy" title="${esc(p.name)} preview" tabindex="-1"></iframe>`:`<img src="${esc(p.previewImage||'assets/steadfast-mark.png')}" alt="${esc(p.name)} preview">`}<span class="sf-preview-label">CLICK TO PREVIEW</span></div><div class="sf-product-body"><div class="sf-product-top"><span>${esc(p.category||"DIGITAL PRODUCT")}</span><strong>${money(p.price,p.currency||"PHP")}</strong></div><h3>${esc(p.name)}</h3><p>${esc(p.description||"")}</p><div class="sf-product-meta"><span>${out?'Out of stock':`${stock} available`}</span><span>${esc(p.paymentMethod||'Manual verification')}</span></div><button class="btn primary full" type="button" data-buy="${esc(p.id)}" ${out?'disabled':''}>${out?'Sold Out':'Buy to Unlock'} <span>→</span></button></div></article>`}
function preview(p){const body=document.getElementById('sfPreviewBody');if(!body)return;body.innerHTML=`<div class="sf-preview-modal-content"><div class="sf-product-preview-large">${p.previewUrl?`<iframe src="${esc(p.previewUrl)}" title="${esc(p.name)} live preview"></iframe>`:`<img src="${esc(p.previewImage||'assets/steadfast-mark.png')}" alt="${esc(p.name)} preview">`}</div><div class="sf-preview-modal-copy"><span class="sf-work-tag">${esc(p.category||'DIGITAL PRODUCT')}</span><h2>${esc(p.name)}</h2><p>${esc(p.description||'')}</p><div class="sf-checkout-price"><span>Fixed price</span><strong>${money(p.price,p.currency||'PHP')}</strong></div><button class="btn primary full" type="button" data-buy="${esc(p.id)}" ${Number(p.stock||0)<1?'disabled':''}>${Number(p.stock||0)<1?'Sold Out':'Buy to Unlock'} <span>→</span></button></div></div>`;document.getElementById('sfPreviewModal').hidden=false;body.querySelector('[data-buy]')?.addEventListener('click',()=>openCheckout(p));}
function openCheckout(p){const code=p.accessCode||"";const modal=document.getElementById('sfPreviewModal'),body=document.getElementById('sfPreviewBody');body.innerHTML=`<div class="sf-preview-modal-copy"><span class="sf-work-tag">SECURE PRODUCT CHECKOUT</span><h2>${esc(p.name)}</h2><p>${esc(p.description||'')}</p><div class="sf-checkout-price"><span>Fixed price</span><strong>${money(p.price,p.currency||'PHP')}</strong></div><form id="sfOrderForm" class="sf-checkout-copy form-like">${code?`<label>Access code<input name="accessCode" required autocomplete="off" placeholder="Enter access code"></label>`:''}<label>Name<input name="name" required placeholder="Your name"></label><label>Email<input name="email" required type="email" placeholder="you@example.com"></label><label>Confirm email<input name="emailConfirm" required type="email" placeholder="Confirm your email"></label><button class="btn primary full" type="submit">Proceed to Payment <span>→</span></button><small>Your order will use the fixed amount shown above. Payment proof is reviewed manually before the product is unlocked.</small></form></div>`;modal.hidden=false;body.querySelector('#sfOrderForm').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);if(p.accessCodeHash){const entered=await hashCode(String(fd.get('accessCode')||''));if(entered!==p.accessCodeHash){alert('Invalid access code.');return}}if(String(fd.get('email')||'').trim().toLowerCase()!==String(fd.get('emailConfirm')||'').trim().toLowerCase()){alert('Email addresses do not match.');return}try{const ref=await addDoc(collection(db,'storeOrders'),{productId:p.id,productName:p.name,customerName:String(fd.get('name')),customerEmail:String(fd.get('email')).trim().toLowerCase(),amount:Number(p.price||0),currency:p.currency||'PHP',paymentMethod:p.paymentMethod||'Manual verification',paymentUrl:p.paymentUrl||'',mariBankLink:p.mariBankLink||'',unlockUrl:p.unlockUrl||'',status:'pending',createdAt:serverTimestamp()});location.href=`pay.html?order=${encodeURIComponent(ref.id)}`;}catch(err){console.error(err);alert('We could not create your order yet. Please try again.')}})}
async function loadStore(){const grid=document.getElementById('steadfastStoreGrid');if(!grid)return;try{const snap=await getDocs(collection(db,'storeProducts'));products=snap.docs.map(d=>({id:d.id,...d.data()})).filter(p=>p.active).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));grid.innerHTML=products.length?products.map(productCard).join(''):`<div class="sf-empty-store"><strong>Digital products coming soon.</strong><span>Products will appear here when published from STEADFAST Admin.</span></div>`;}catch(e){console.warn(e);grid.innerHTML=`<div class="sf-empty-store"><strong>Store setup in progress.</strong><span>Please try again shortly.</span></div>`}}
document.addEventListener('click',e=>{const close=e.target.closest('[data-close-preview]');if(close)document.getElementById('sfPreviewModal').hidden=true;const pb=e.target.closest('[data-preview]');if(pb)preview(products.find(p=>p.id===pb.dataset.preview));const buy=e.target.closest('[data-buy]');if(buy&&!buy.closest('#sfPreviewBody'))openCheckout(products.find(p=>p.id===buy.dataset.buy));});
loadStore();
