import { initializeApp, getApps } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import { getFirestore, collection, addDoc, setDoc, doc, serverTimestamp, onSnapshot, query, where, writeBatch } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyD13MXR0ZQSjPJBxQKYPmsMKjl4yzU2hSs",authDomain:"steadfast-1d0e6.firebaseapp.com",projectId:"steadfast-1d0e6",storageBucket:"steadfast-1d0e6.firebasestorage.app",messagingSenderId:"488385339804",appId:"1:488385339804:web:0d2bcf3967a8f95ccfe859"};
const app=getApps().length?getApps()[0]:initializeApp(firebaseConfig),db=getFirestore(app);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=(v,c="PHP")=>{try{return new Intl.NumberFormat(undefined,{style:"currency",currency:c}).format(Number(v||0))}catch{return `${c} ${Number(v||0).toFixed(2)}`}};
let products=[];
function showSystemError(title, detail){const box=document.getElementById("sfSystemError");if(!box)return;document.getElementById("sfSystemErrorTitle").textContent=title||"Something went wrong.";document.getElementById("sfSystemErrorDetail").textContent=detail||"Please try again.";box.hidden=false;}
document.getElementById("sfSystemErrorClose")?.addEventListener("click",()=>{document.getElementById("sfSystemError").hidden=true});

async function hashCode(value){const data=new TextEncoder().encode(value);const hash=await crypto.subtle.digest("SHA-256",data);return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,"0")).join("");}
function imgs(p){return Array.isArray(p.previewImages)?p.previewImages.filter(Boolean):[];}
function mainPreview(p){const list=imgs(p);if(p.previewUrl)return `<iframe src="${esc(p.previewUrl)}" loading="lazy" title="${esc(p.name)} preview" tabindex="-1"></iframe>`;if(list[0])return `<img src="${esc(list[0])}" alt="${esc(p.name)} preview">`;return `<div class="sf-preview-empty">LIVE PREVIEW</div>`}
function productCard(p){const stock=Math.max(0,Number(p.stock||0)),out=stock<1;return `<article class="sf-product-card"><div class="sf-product-preview sf-preview-button" role="button" tabindex="0" data-preview="${esc(p.id)}" aria-label="Preview ${esc(p.name)}">${mainPreview(p)}<span class="sf-preview-label">CLICK TO PREVIEW</span></div><div class="sf-product-body"><div class="sf-product-top"><span>DIGITAL PRODUCT</span><strong>${money(p.price,p.currency||"PHP")}</strong></div><h3>${esc(p.name)}</h3><p>${esc(p.description||"")}</p><div class="sf-product-meta"><span>${out?'Out of stock':`${stock} available`}</span><span>${esc(p.paymentMethod||'Manual verification')}</span></div><button class="btn primary full" type="button" data-buy="${esc(p.id)}" ${out?'disabled':''}>${out?'Sold Out':'Buy to Unlock'} <span>→</span></button></div></article>`}
function preview(p){const body=document.getElementById('sfPreviewBody');if(!body)return;const list=imgs(p);body.innerHTML=`<div class="sf-preview-modal-content"><div><div class="sf-product-preview-large" id="previewMain">${mainPreview(p)}</div>${list.length>1?`<div class="sf-preview-gallery">${list.map((x,i)=>`<button type="button" data-gallery="${i}"><img src="${esc(x)}" alt="Preview ${i+1}"></button>`).join('')}</div>`:''}</div><div class="sf-preview-modal-copy"><span class="sf-work-tag">DIGITAL PRODUCT</span><h2>${esc(p.name)}</h2><p>${esc(p.description||'')}</p><div class="sf-checkout-price"><span>Fixed price</span><strong>${money(p.price,p.currency||'PHP')}</strong></div><button class="btn primary full" type="button" data-buy="${esc(p.id)}" ${Number(p.stock||0)<1?'disabled':''}>${Number(p.stock||0)<1?'Sold Out':'Buy to Unlock'} <span>→</span></button></div></div>`;document.getElementById('sfPreviewModal').hidden=false;body.querySelectorAll('[data-gallery]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.gallery),m=document.getElementById('previewMain');if(m&&list[i])m.innerHTML=`<img src="${esc(list[i])}" alt="Preview ${i+1}">`}));body.querySelector('[data-buy]')?.addEventListener('click',()=>openCheckout(p));}
function openCheckout(p){const code=p.accessCodeHash||"";const modal=document.getElementById('sfPreviewModal'),body=document.getElementById('sfPreviewBody');body.innerHTML=`<div class="sf-preview-modal-copy"><span class="sf-work-tag">SECURE PRODUCT CHECKOUT</span><h2>${esc(p.name)}</h2><p>${esc(p.description||'')}</p><div class="sf-checkout-price"><span>Fixed price</span><strong>${money(p.price,p.currency||'PHP')}</strong></div><form id="sfOrderForm" class="sf-checkout-copy form-like">${code?`<label>Access code<input name="accessCode" required autocomplete="off" placeholder="Enter access code"></label>`:''}<label>Name<input name="name" required placeholder="Your name"></label><label>Email<input name="email" required type="email" placeholder="you@example.com"></label><label>Confirm email<input name="emailConfirm" required type="email" placeholder="Confirm your email"></label><button class="btn primary full" type="submit">Proceed to Payment <span>→</span></button><small>Your order will use the fixed amount shown above. Payment proof is reviewed manually before unlocking.</small></form></div>`;modal.hidden=false;body.querySelector('#sfOrderForm').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);if(p.accessCodeHash){const entered=await hashCode(String(fd.get('accessCode')||''));if(entered!==p.accessCodeHash){alert('Invalid access code.');return}}if(String(fd.get('email')||'').trim().toLowerCase()!==String(fd.get('emailConfirm')||'').trim().toLowerCase()){alert('Email addresses do not match.');return}try{const orderRef=doc(collection(db,'storeOrders'));const checkoutRef=doc(db,'storeCheckout',orderRef.id);const createdAt=serverTimestamp();const batch=writeBatch(db);batch.set(orderRef,{productId:p.id,productName:p.name,customerName:String(fd.get('name')),customerEmail:String(fd.get('email')).trim().toLowerCase(),amount:Number(p.price||0),currency:p.currency||'PHP',paymentMethod:p.paymentMethod||'Manual verification',paymentUrl:p.paymentUrl||'',mariBankLink:p.mariBankLink||'',unlockUrl:p.unlockUrl||'',accessUsername:p.accessUsername||'',accessPassword:p.accessPassword||'',status:'pending',createdAt});batch.set(checkoutRef,{productName:p.name,customerName:String(fd.get('name')),description:p.description||'',amount:Number(p.price||0),currency:p.currency||'PHP',paymentMethod:p.paymentMethod||'Manual verification',paymentUrl:p.paymentUrl||'',mariBankLink:p.mariBankLink||'',unlockUrl:p.unlockUrl||'',status:'pending',createdAt});await batch.commit();location.href=`pay.html?order=${encodeURIComponent(orderRef.id)}`;}catch(err){console.error(err);showSystemError('Could not create checkout order.', `Problem identified: ${err?.code||err?.message||'temporary Firebase error'}`);}})}
function loadStore(){const grid=document.getElementById('steadfastStoreGrid');if(!grid)return;onSnapshot(query(collection(db,'storeProducts'), where('active','==',true)),snap=>{products=snap.docs.map(d=>({id:d.id,...d.data()})).filter(p=>p.active).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));grid.innerHTML=products.length?products.map(productCard).join(''):`<div class="sf-empty-store"><strong>No products available.</strong><span>There are no products available in the STEADFAST Store right now.</span></div>`},e=>{console.warn(e);showSystemError('Store could not load.', `Problem identified: ${e?.code||e?.message||'temporary Firebase connection or permission issue'}`);grid.innerHTML=`<div class="sf-empty-store sf-service-error"><strong>Store temporarily unavailable.</strong><span>We’re having trouble connecting to the Store service right now.</span><small>Problem identified: ${esc(e?.code||e?.message||'temporary Firebase connection or permission issue')}</small><button class="btn ghost" type="button" onclick="window.location.reload()">Try Again</button></div>`})}
document.addEventListener('click',e=>{const close=e.target.closest('[data-close-preview]');if(close)document.getElementById('sfPreviewModal').hidden=true;const pb=e.target.closest('[data-preview]');if(pb)preview(products.find(p=>p.id===pb.dataset.preview));const buy=e.target.closest('[data-buy]');if(buy&&!buy.closest('#sfPreviewBody'))openCheckout(products.find(p=>p.id===buy.dataset.buy));});
loadStore();
