const state={quotes:[
{id:1,name:'John Smith',type:'E-commerce',price:'2,400',currency:'USD',status:'New',date:'Sep 19, 2026',email:'john@example.com'},
{id:2,name:'Maria Santos',type:'Business Website',price:'45,000',currency:'PHP',status:'Contacted',date:'Sep 18, 2026',email:'maria@example.com'},
{id:3,name:'Alex Chen',type:'Portfolio Website',price:'1,200',currency:'CAD',status:'Proposal Sent',date:'Sep 18, 2026',email:'alex@example.com'},
{id:4,name:'Sarah Miller',type:'Restaurant Website',price:'3,200',currency:'USD',status:'In Progress',date:'Sep 17, 2026',email:'sarah@example.com'},
{id:5,name:'Daniel Kim',type:'Web Application',price:'5,000',currency:'AUD',status:'New',date:'Sep 17, 2026',email:'daniel@example.com'}]};
const metrics=[['▤','12','New Quotes','↑ 20%'],['◷','7','Pending','↑ 14%'],['➤','3','Contacted','↑ 50%'],['⚙','2','In Progress','→ 0%'],['✓','5','Converted','↑ 67%']];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),2200)}
function route(page){$$('.page').forEach(p=>p.classList.toggle('active-page',p.dataset.page===page));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route===page));$('#sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});history.replaceState(null,'',`#${page}`)}
function renderMetrics(){$('#metrics').innerHTML=metrics.map(m=>`<div class="metric"><div class="metric-icon">${m[0]}</div><div><strong>${m[1]}</strong><span>${m[2]}</span><small>${m[3]} <span style="display:inline;color:#73829b">vs last week</span></small></div></div>`).join('')}
function statusClass(s){return s==='New'?'status-new':s==='Contacted'?'status-contacted':s==='Proposal Sent'?'status-proposal':'status-progress'}
function quoteRows(list,target='#quotesBody'){const el=$(target);if(!el)return;el.innerHTML=list.map(q=>`<tr><td>${q.id}</td><td><strong>${q.name}</strong></td><td>${q.type}</td><td>${q.price}</td><td>${q.currency}</td><td><span class="status-pill ${statusClass(q.status)}">${q.status}</span></td><td>${q.date}</td><td><button class="table-action" data-view="${q.id}">View</button></td></tr>`).join('')||`<tr><td colspan="8" style="text-align:center;color:#71809a;padding:25px">No quotations found.</td></tr>`}
function renderQuotes(){quoteRows(state.quotes);quoteRows(state.quotes,'#allQuotesBody')}
function renderIntegrations(){$('#integrations').innerHTML=[['✉','Gmail','Send emails directly from your account.'],['◉','CRM (e.g. HubSpot, Zoho)','Sync leads automatically.'],['▤','Google Sheets','Export quotations to Sheets.']].map(x=>`<div class="integration-row"><div class="app-icon">${x[0]}</div><div><strong>${x[1]}</strong><small>${x[2]}</small></div><span class="connected-dot">● Connected</span></div>`).join('')}
function renderPipeline(){const groups=['New','Contacted','Proposal Sent','In Progress'];$('#pipeline').innerHTML=groups.map(s=>`<div class="pipeline-col"><h3>${s}</h3>${state.quotes.filter(q=>q.status===s).map(q=>`<div class="lead-card"><strong>${q.name}</strong><small>${q.type} · ${q.currency} ${q.price}</small><button class="table-action" style="margin-top:8px" data-view="${q.id}">Open</button></div>`).join('')||'<small style="color:#65758e">No leads</small>'}</div>`).join('')}
function renderClients(){const unique=[...new Map(state.quotes.map(q=>[q.name,q])).values()];$('#clientGrid').innerHTML=unique.map(q=>`<div class="card client-card"><div class="avatar">${q.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><h3>${q.name}</h3><p>${q.email}</p><span class="status-pill ${statusClass(q.status)}">${q.status}</span></div></div>`).join('')}
function openQuote(id){const q=state.quotes.find(x=>x.id==id);if(!q)return;$('#modalContent').innerHTML=`<p class="eyebrow">WEBSITE QUOTATION #${q.id}</p><h2>${q.name}</h2><p style="color:#8e9bb2">Review the inquiry details below.</p><div class="modal-data"><div><small>Website Type</small><strong>${q.type}</strong></div><div><small>Estimated Price</small><strong>${q.currency} ${q.price}</strong></div><div><small>Email</small><strong>${q.email}</strong></div><div><small>Date</small><strong>${q.date}</strong></div><div><small>Status</small><strong>${q.status}</strong></div><div><small>Lead Source</small><strong>Website Quotation</strong></div></div><div style="display:flex;gap:9px;margin-top:18px;flex-wrap:wrap"><button class="primary-btn" onclick="updateQuote(${q.id})">Update Status</button><button class="outline-btn" onclick="showToast('Email draft opened');closeModal()">Email Client</button></div>`;$('#modal').classList.add('open')}
function updateQuote(id){const q=state.quotes.find(x=>x.id==id);const next={New:'Contacted',Contacted:'Proposal Sent','Proposal Sent':'In Progress','In Progress':'Completed'}[q.status]||'New';q.status=next;renderQuotes();renderPipeline();closeModal();showToast(`${q.name} moved to ${next}`)}
function closeModal(){$('#modal').classList.remove('open')}
function exportCSV(){const head='Client,Website Type,Estimated Price,Currency,Status,Date,Email\n';const csv=head+state.quotes.map(q=>[q.name,q.type,q.price,q.currency,q.status,q.date,q.email].map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='steadfast-quotations.csv';a.click();URL.revokeObjectURL(url);showToast('Quotation CSV exported')}
function composeEmail(){openModalHTML(`<p class="eyebrow">COMMUNICATION</p><h2>Compose Email</h2><label style="display:grid;gap:7px;color:#95a2b7;font-size:11px;margin:12px 0">To<input class="toolbar input" id="emailTo" placeholder="client@example.com"></label><label style="display:grid;gap:7px;color:#95a2b7;font-size:11px;margin:12px 0">Subject<input id="emailSubject" placeholder="Thank you for your inquiry"></label><label style="display:grid;gap:7px;color:#95a2b7;font-size:11px;margin:12px 0">Message<textarea id="emailBody" rows="7" style="background:#09162a;color:#fff;border:1px solid #2a405f;border-radius:8px;padding:11px">Hello,\n\nThank you for your website inquiry. I’ll review your requirements and get back to you with the next steps.\n\nSTEADFAST</textarea></label><button class="primary-btn" onclick="showToast('Email draft prepared');closeModal()">Prepare Email</button>`)}
function openModalHTML(html){$('#modalContent').innerHTML=html;$('#modal').classList.add('open')}
function filterQuotes(){const q=($('#quoteFilter')?.value||'').toLowerCase(),s=$('#statusFilter')?.value||'all';quoteRows(state.quotes.filter(x=>(s==='all'||x.status===s)&&`${x.name} ${x.type} ${x.email}`.toLowerCase().includes(q)),'#allQuotesBody')}
function init(){renderMetrics();renderQuotes();renderIntegrations();renderPipeline();renderClients();const hash=location.hash.slice(1);if(hash&&$(`.page[data-page="${hash}"]`))route(hash);document.addEventListener('click',e=>{const routeBtn=e.target.closest('[data-route]');if(routeBtn){route(routeBtn.dataset.route);return}const view=e.target.closest('[data-view]');if(view){openQuote(view.dataset.view);return}const action=e.target.closest('[data-action]');if(action){const a=action.dataset.action;if(a==='csv')exportCSV();if(a==='email')composeEmail();if(a==='newQuote')showToast('Use the public Website Quotation page to submit a new inquiry.');if(a==='template')composeEmail();if(a==='connectCRM')showToast('CRM connection ready for OAuth setup.');if(a==='saveSettings')showToast('Settings saved locally for this demo.');if(a==='map')showToast('Map view opened (demo).');return}});$('#globalSearch').addEventListener('input',e=>{const val=e.target.value.trim().toLowerCase();if(val){route('quotations');$('#quoteFilter').value=val;filterQuotes()}});$('#quoteFilter').addEventListener('input',filterQuotes);$('#statusFilter').addEventListener('change',filterQuotes);$('#mobileMenu').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));$('#modalClose').addEventListener('click',closeModal);$('.modal-backdrop').addEventListener('click',closeModal);$('#viewWebsite').addEventListener('click',()=>window.open('../index.html','_self'));$('#notificationBtn').addEventListener('click',()=>showToast('3 quotation notifications'));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()})}
init();
